### ISSUE TITLE
support for on-prem BB to AzureRepos 

### ISSUE THREAD

**Issue by shzshi** [kunduso/MigrateToAzureRepos#8]
Hi, 

This script is really nice , but does it support on premises hosted bitbucket project to azure  repos , if yes then can you please guide ? 

Cheers,
Shashi

**Comment by kunduso** [comment]
Hi Shashi,
I have not tried this on  on-prem hosted BitBucket. You can run the script and to be safe, comment out the following lines before you run:
```
            #Region Migration
            $ProjectCloneURL = $BitbucketCloneUrl+$ProjectRepos.full_name+".git"
            . CloneReposFromBitBucket ($RootFolderForProjects) ($ProjectCloneURL) ($ProjectRepos.slug)
            . CreateEmptyAzureRepo ($ProjectRepos.slug)
            . PushCodeFromLocalToEmptyAzureRepo ($RootFolderForProjects) ($ProjectRepos.slug)
            #endregion
```
Let me know if you face any errors.
